//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HowToWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HowToDbEntities : DbContext
    {
        public HowToDbEntities()
            : base("name=HowToDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articleCategories> articleCategories { get; set; }
        public virtual DbSet<articles> articles { get; set; }
        public virtual DbSet<articlesTags> articlesTags { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<favourites> favourites { get; set; }
        public virtual DbSet<images> images { get; set; }
        public virtual DbSet<ratings> ratings { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<requestsArticles> requestsArticles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<usersCategories> usersCategories { get; set; }
        public virtual DbSet<websiteInfos> websiteInfos { get; set; }
    }
}
